version: '3'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - '3304:3306'
    environment:
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'newuser'
       MYSQL_ROOT_PASSWORD: 'password'
       MYSQL_PASSWORD: 'password'
  web:
    image: django
    container_name: frontend-cont
    build: .
    command: bash -c "python3 app/manage.py migrate && python3 app/manage.py runserver 0.0.0.0:8000"
    
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
